"""
Django settings for carsharing project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# BASE_DIR указывает на корневую папку нашего проекта.
BASE_DIR = Path(__file__).resolve().parent.parent


# Это настройки для быстрого старта проекта. Не используйте их в продакшене!

# Секретный ключ для шифрования данных. Храните его в секрете!
SECRET_KEY = 'django-insecure-o_=2!ywkcdtw9h$c$7tojtfza=w)qj7wy)*l$z_7_h82ptmm@0'

# Включите режим отладки только для разработки. В продакшене это должно быть False.
DEBUG = True

# Список хостов, с которых разрешены запросы к вашему проекту. Пока он пустой.
ALLOWED_HOSTS = []


# Определение установленных приложений. Это те приложения, которые включены в ваш проект.
INSTALLED_APPS = [
    'django.contrib.admin',  # Админка
    'django.contrib.auth',  # Аутентификация
    'django.contrib.contenttypes',  # Типы контента
    'django.contrib.sessions',  # Сессии
    'django.contrib.messages',  # Сообщения
    'django.contrib.staticfiles',  # Статические файлы
    'rental',  # Наше приложение аренды
    'tempus_dominus',  # Виджеты для выбора даты и времени
]

# Промежуточные слои обработки запросов. Здесь указаны все middlewares, которые будут выполняться на каждом запросе.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Указывает на основной файл конфигурации URL'ов вашего проекта.
ROOT_URLCONF = 'carsharing.urls'

# Настройки для шаблонов (HTML файлов).
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Указывает на файл конфигурации WSGI, который используется для развертывания проекта.
WSGI_APPLICATION = 'carsharing.wsgi.application'


# Настройки базы данных. В данном случае используется SQLite, что удобно для разработки.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Настройки валидаторов паролей. Они помогают делать пароли более безопасными.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Настройки интернационализации (переводы, временные зоны и т.д.)
LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Настройки для статических файлов (CSS, JavaScript, изображения).
STATIC_URL = 'static/'

# Настройки для перенаправления после входа и выхода из аккаунта.
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Настройки для поля с первичным ключом по умолчанию.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
